---
title: "Pocillopora genotype origin map"
author: "Mike Connelly"
date: "01/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```
```{r packages, message=FALSE}
library("raster") #for processing some spatial data
library("rnaturalearth") #for downloading shapefiles
library("sf") #for processing shapefiles
library("elevatr") #for downloading elevation data
library("dplyr") #to keep things tidy
library("magrittr") #to keep things very tidy
library("ggspatial") #for scale bars and arrows
library("ggplot2") #for tidy plotting
library("ggpubr") #for easy selection of symbols
library("colourpicker") #for easy selection of colors
library("rnaturalearthhires")
library("maps") # for getting pacific-centered map
library("scatterpie") # for plotting proportions of different lineages on map
library("ggnewscale") # for adding new fill scale to keep elevation
library("ggrepel") # for adding labels to plot
```
```{r load shapefiles, message=FALSE}
# Load shapefiles from rnaturalearth package
map <- ne_countries(scale = 10, returnclass = "sf")
# 
states <- ne_states(returnclass = "sf")
# 
ocean <- ne_download(scale = 10, type = 'ocean', 
                   category = 'physical', returnclass = 'sf')
# 
rivers <- ne_download(scale = 10, type = 'rivers_lake_centerlines', 
                    category = 'physical', returnclass = 'sf')
# 
reefs <- ne_download(scale = 10, type = 'reefs',
                     category = "physical", returnclass = 'sf')
```
```{r Quick check on basic shapefiles, echo = FALSE, fig.align= "center", fig.width= 6}
quickCheck <-
  ggplot() +
  geom_sf(data = ocean, color = "black", size = 0.05, fill = "#def3f6") +
  geom_sf(data = reefs, color = "red", size = 0.05, fill = "red") +
  geom_sf(data = rivers, color = "blue", size = 0.05) +
  geom_sf(data = states, color = "black", size = 0.05, fill = "#f5f5f5", alpha = 0.5) +
  theme(panel.grid.major = element_blank(), 
        panel.background = element_blank(), 
        panel.border = element_rect(fill = NA))
par(mar = c(0.5, 0.5, 0.5, 0.5))
quickCheck
```

```{r}
focalArea <- map %>% filter(admin == "Panama")
```
```{r define map extent}
limit <- st_buffer(focalArea, dist = 0.1) %>% st_bbox()

clipLimit <- st_buffer(focalArea, dist = 0.5) %>% st_bbox()

limitExtent <- as(extent(clipLimit), 'SpatialPolygons')

crs(limitExtent) <- "+proj=longlat +datum=WGS84 +no_defs"
```
```{r Show map and clipping extent, echo = FALSE, fig.align= "center", warning = FALSE}
par(mar = c(0.5, 0.5, 0.5, 0.5))
plot(as(extent(clipLimit), 'SpatialPolygons'), lty="dashed")
plot(as(extent(limit), 'SpatialPolygons'), add = TRUE)
plot(focalArea, col = "#005293", add = TRUE)
```

```{r obtain elevation data}
elev<-get_elev_raster(locations = limitExtent, z = 6, override_size_check = T)

elevDF<-as.data.frame(elev, xy=TRUE)

colnames(elevDF)<-c("x", "y", "elevation")

elevDF[, 3][elevDF[, 3] < 1500] <- NA
```

```{r Test elevation map, echo = FALSE, fig.align= "center", warning = FALSE}
par(mar = c(0.5, 0.5, 0.5, 0.5))
elevMapTest <-
  ggplot() +
  geom_tile(data = elevDF, aes(x=x, y=y, fill=elevation), alpha =0.4)+
  scale_fill_gradient(low="#a3a0a0", high= "#000000", 
                      na.value="transparent")+
  geom_sf(data = ocean, color = "black", size = 0.05, fill = "#add8e6")+
  geom_sf(data = rivers, color = "#d7f2fa", size = 0.5)+
  geom_sf(data = states, color = "black", size = 0.05, fill = "#f5f5f5", alpha = 0.2)+
  geom_sf(data = map, color = "black", size = 0.1, fill = "#f5f5f5", alpha = 0.2)+
    coord_sf(
    xlim = c(limit["xmin"], limit["xmax"]),
    ylim = c(limit["ymin"], limit["ymax"])) +
  labs(x="Longitude", y="Latitude", elevation = "Elevation") +
  theme(panel.grid.major = element_blank(),
  panel.background = element_rect(fill = "#f0f8ff"),
  panel.border = element_rect(fill = NA))
  ggtitle(title)
elevMapTest
```

## Plot proportions of *Pocillopora* mtORF lineages on map with scatterpie
```{r genotypes}
genotypes <- read_csv("data/genotypes.csv")
coordinates <- read_csv("data/gulfs_coordinates.csv")
#
locations_mtorfs <- genotypes %>% 
  group_by(Gulf, mtORF) %>% 
  dplyr::count() %>% 
  pivot_wider(names_from = mtORF, values_from = n, values_fill = 0) %>% 
  dplyr::rename("Type 1" = Type_1, "Type 3" = Type_3) %>% 
  mutate("radius" = (`Type 1` + `Type 3`)/20) %>% 
  left_join(coordinates, by = "Gulf")
```
### Figure 1A
```{r figure 1A: powerpoint}
pdf(file="./outputs/figures/Pocillopora_origins_map_scatterpie.pdf", width = 8, height = 4)
title <- expression('Panama '*italic("Pocillopora")*' genotype origins and mitochondrial lineages')
par(mar = c(0.5, 0.5, 0.5, 0.5))
elevMapTest <-
  ggplot() +
  geom_sf(data = ocean, color = "black", size = 0.1, fill = "aliceblue") +
  geom_sf(data = states, color = "black", size = 0.1, fill = "antiquewhite", alpha = 0.5) +
  geom_sf(data = map, color = "black", size = 0.2, fill = "antiquewhite", alpha = 0.5) +
  geom_tile(data = elevDF, aes(x = x, y = y, fill = elevation), alpha = 0.4, show.legend = FALSE) +
  scale_fill_gradient(low="antiquewhite3", high= "black",
                      na.value="transparent", name = "Elevation (m)")+
  geom_sf(data = rivers, color = "royalblue3", size = 0.15) +
    coord_sf(
    xlim = c(limit["xmin"], limit["xmax"]),
    ylim = c(limit["ymin"], limit["ymax"])) +
  #
  new_scale_fill() +
  geom_scatterpie(aes(x = Longitude, y = Latitude, group = Gulf, r = radius),
                    data = locations_mtorfs, cols = c("Type 1", "Type 3"), alpha = .8) + 
  scale_fill_manual(values = c("darkorange1", "turquoise2"), name = "mtORF Type") +
  #
  labs(x="Longitude", y="Latitude", elevation = "Elevation") +
  theme(panel.grid.major = element_blank(),
        panel.background = element_rect(fill = "#f0f8ff"),
        panel.border = element_rect(fill = NA),
        plot.title = element_text(size = 16),
        axis.title = element_text(size = 14), 
        axis.text = element_text(size = 10),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 10)) +
  ggtitle(title)
elevMapTest
dev.off()
```
```{r figure 1A: manuscript}
pdf(file="./outputs/figures/Fig1A_pocillopora_origins_map_scatterpie.pdf", height = 90/25.4, width = 160/25.4) # two-column max size
title <- expression('Panama '*italic("Pocillopora")*' genotype origins and mitochondrial lineages')
par(mar = c(0.5, 0.5, 0.5, 0.5))
elevMapTest <-
  ggplot() +
  geom_sf(data = ocean, color = "black", size = 0.1, fill = "aliceblue") +
  geom_sf(data = states, color = "black", size = 0.1, fill = "antiquewhite", alpha = 0.5) +
  geom_sf(data = map, color = "black", size = 0.2, fill = "antiquewhite", alpha = 0.5) +
  geom_tile(data = elevDF, aes(x = x, y = y, fill = elevation), alpha = 0.4, show.legend = FALSE) +
  scale_fill_gradient(low="antiquewhite3", high= "black",
                      na.value="transparent", name = "Elevation (m)")+
  geom_sf(data = rivers, color = "royalblue3", size = 0.15) +
    coord_sf(
    xlim = c(limit["xmin"], limit["xmax"]),
    ylim = c(limit["ymin"], limit["ymax"])) +
  #
  new_scale_fill() +
  geom_scatterpie(aes(x = Longitude, y = Latitude, group = Gulf, r = radius),
                    data = locations_mtorfs, cols = c("Type 1", "Type 3"), alpha = .8) + 
  scale_fill_manual(values = c("darkorange1", "turquoise2"), name = "mtORF Type") +
  #
  labs(x="Longitude", y="Latitude", elevation = "Elevation") +
  theme(panel.grid.major = element_blank(),
        panel.background = element_rect(fill = "#f0f8ff"),
        panel.border = element_rect(fill = NA),
        plot.title = element_text(size = 12),
        axis.title = element_text(size = 10), 
        axis.text = element_text(size = 8),
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 8)) +
  ggtitle(title)
elevMapTest
dev.off()
```
