---
title: "IPAM_analysis"
author: "Mike Connelly"
date: "7/12/2020"
output: html_document
---
## Setup directories and packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/computing/projects/anti_phys")
```
```{r packages}
library("tidyverse")
library("ggplot2")
library("ggh4x") # devtools::install_github("teunbrand/ggh4x") 
# library("ggpubr")
# library("ggnewscale")
```
```{r colors, include=FALSE}
#rename to named colors
treatcolors <- c("lightblue", "dodgerblue", "seagreen1")
#treatfills <- c()
genotype_colors <- read_csv("data/genotype_colors.csv") # color names csv corresponding to excel sheet colors
genocolors <- c(genotype_colors$color, "grey")
```
```{r theme}
theme_set(theme_bw())
```
## Import sample metadata
```{r genotypes_fragments, include=FALSE}
genotypes <- read_csv("data/genotypes.csv")
#
fragments <- read_csv("data/fragments.csv", col_types = cols(
  Fragment_ID = col_character()))
```
```{r factors}
# factor levels
treatment_levels <- c("Baseline", "Control", "Antibiotics")
sampling_levels <- c("Day 0", "Day 7")
day_levels <- c("day1", "day2", "day3", "day4", "day5")
genotype_levels <- c("PAN-05", "PAN-10", "PAN-32", "PAN-34", "PAN-35", "PAN-37", "PAN-39", "PAN-41", "PAN-43","PAN-44", "PAN-78", "PAN-79", "PAN-83", "URA-51", NA)
gulf_levels <- c("Chiriqui", "Panama")
loc_levels <- c("Uva", "Saboga", "Uraba")
mtorf_levels <- c("Type_1", "Type_3")
sym_levels <- c("C1bc", "C1d", "D1")
```
## Import plate fragment-position keys
```{r plate_keys,include = FALSE}
# Fragment positions in the 24-well plates were randomized each day during media changes, and positions were maintained through the IPAM assessment, microscopy imaging, and microplate respirometry
# Information about which fragments or blank wells were in which position needs to be imported and made to correspond with the appropriate AOI information (IPAM) and well position information (respirometry) in the imported source data

# Import IPAM area of interest (AOI) to fragment ID keys to later connect measurements to sample metadata
plate_keys <- list.files(path = "./data/plate_keys", pattern = "plate_key_d[[:digit:]]\\.csv", full.names = T)

# Check to ensure all files are present
plate_keys

# Create lookup table for AOI_ID from Well_ID
wells_aoi <- c("A1" = 1, "A2" = 2, "A3" = 3, "A4" = 4, "A5" = 5, "A6" = 6,
               "B1" = 7, "B2" = 8, "B3" = 9, "B4" = 10, "B5" = 11, "B6" = 12,
               "C1" = 13, "C2" = 14, "C3" = 15, "C4" = 16, "C5" = 17, "C6" = 18,
               "D1" = 19, "D2" = 20, "D3" = 21, "D4" = 22, "D5" = 23, "D6" = 24)
aoi_levels <- as.character(1:24)

# Import all plate keys 
plate_key_master <- plate_keys %>%
  map_dfr(read_csv) %>% 
  dplyr::select(Meas_Day, Sample_ID, Fragment_ID, Plate_Well_ID) %>% 
  arrange(Sample_ID) %>% 
  separate(col = Plate_Well_ID, into = c("Plate", "Well"), sep = "-")

# Add column that converts the well ID information into AOI for IPAM
plate_key_master$AOI <- as.character(unname(wells_aoi[plate_key_master$Well]))

# Unite into one dataframe
plate_key_master <- plate_key_master %>% 
  unite(AOI_ID, Plate, AOI, sep = "_", remove = FALSE) %>% 
  unite(AOI_ID_key, Meas_Day, AOI_ID, sep = "_", remove = FALSE) %>% 
  unite(Well_ID, Plate, Well, sep = "_", remove = FALSE) %>% 
  unite(Well_ID_key, Meas_Day, Well_ID, sep = "_", remove = FALSE) %>% 
  arrange(Well_ID_key)

# Attach metadata from keys
day_plate <- plate_key_master %>% 
  arrange(Well_ID_key)
```
## Import IPAM data files
```{r ipam_data, message=FALSE, warning=FALSE}
# List all plate information files in the target import directory
ipam_data_files <- list.files(path = "./data/ipam", pattern = "*.csv", full.names = T)
# name files for easier parsing of path contents including measurement day (day1 - day7), plate number (plate1 - plate6), and date (MMDDYY)
# example path: "./data/ipam/ipam_day1_plate1_083120.csv
# check file paths
ipam_data_files

# import all ipam files to data frame
ipam_plates_df <- sapply(ipam_data_files[1:30], # ignore ipam measurements taken at sampling time (day 5 positions)
                         read_delim,
                         delim = ";",
                         col_types = cols(
                           .default = col_double(),
                           Date = col_character(),
                           Time = col_time(format = ""),
                           X77 = col_skip()
                           ),
                         simplify=FALSE) %>% 
  bind_rows(.id = "path")

# check ipam data frame
ipam_plates_df
# 163 obs. of 77 variables
```

```{r ipam_tidy}
ipam_plates_data <- ipam_plates_df %>% 
  # filter only three measurements after initial F0 record on 60-second intervals
  filter(No. < 5 & No. > 1) %>% 
  # regex to parse measurement day and plate number
  tidyr::extract(col = path, into = c("Meas_Day", "Plate", "Date_B"), regex = "^./data/ipam/(day[0-7])_plate([[:alnum:]]{1,2})_([[:digit:]]{6}).csv$") 

# Tidy data according to initial format and sample AOI information
ipam_tidy <- ipam_plates_data %>%
  dplyr::select(-Date, -Time, -PAR) %>% 
  dplyr::select(Meas_Day:No., "Y(II)1":"Y(II)24") %>% 
  pivot_longer(., cols = ("Y(II)1":"Y(II)24"), names_to = "parameter_AOI", values_to = "value") %>% 
  # extract plate number and AOI/well number into different columns
  extract(col = parameter_AOI, into = c("parameter", "AOI"), regex = "(Y\\(II\\))([[:digit:]]{1,2})") 
# yields 2160 x 7 data frame
```
```{r ipam_key_link}
# Match corresponding AOIs to Fragment IDs or blanks 
ipam_tidied <- ipam_tidy %>%
  unite(AOI_ID, Plate, AOI, sep = "_", remove = FALSE) %>% 
   unite(AOI_ID_key, Meas_Day, AOI_ID, sep = "_", remove = FALSE)

# Process tidy ipam data
ipam_complete <- ipam_tidied %>% 
  group_by(Meas_Day, AOI_ID) %>% 
  # summarize across three replicates to obtain averaged Y(II) values for 144 wells (24x6)
  dplyr::summarise(mean_value = mean(value)) %>%
  unite(AOI_ID_key, Meas_Day, AOI_ID, sep = "_", remove = FALSE) %>% 
  # join with plate key to obtain fragment positions
  left_join(plate_key_master, by = "AOI_ID_key") %>% 
  dplyr::select(-contains(".y")) %>%
  dplyr::rename(AOI_ID = AOI_ID.x, Meas_Day = Meas_Day.x) %>%
  # join with fragments and genotypes to link metadata
  left_join(fragments, by = "Fragment_ID") %>%
  left_join(genotypes, by = "Genotype")
# yields 720 x 20 data frame

# set factor levels
ipam_complete$Genotype <- factor(ipam_complete$Genotype, levels = genotype_levels, ordered = TRUE)
ipam_complete$Treatment <- factor(ipam_complete$Treatment, levels = treatment_levels, ordered = TRUE)
ipam_complete$Meas_Day <- factor(ipam_complete$Meas_Day, levels = day_levels, ordered = TRUE)
```
```{r filter fragments}
ipam_fragments <- ipam_complete %>% 
  filter(Sample_ID != "b")
ipam_fragments$Day<-as.integer(ipam_fragments$Meas_Day)
ipam_fragments$DayF <- factor(ipam_fragments$Day)
```
## Exploratory visualizations
```{r single-day_ipam_boxplot}
ipam_boxplot <- ipam_complete %>% 
  filter(Meas_Day == "day5") %>% 
  ggplot(aes(Genotype, mean_value, fill = Genotype)) +
  geom_boxplot() +
  geom_jitter(shape = 21) +
  geom_point() +
  # ylim(c(0.0, 0.8)) +
  scale_fill_manual(values = genocolors)
ipam_boxplot
# ggsave("outputs/figures/ipam_day5_boxplot.pdf", ipam_boxplot,  device = "pdf", height = 4, width = 10)
```
```{r daily_ipam_treatment_comp}
ipam_fragments %>% 
  ggplot(aes(Treatment, mean_value, fill = Genotype)) +
  geom_boxplot() +
  geom_jitter(shape = 21) +
  geom_point() +
  facet_grid(~Genotype) +
  ylim(c(0.0, 0.8)) +
  scale_fill_manual(values = genocolors)
```

```{r }
ipam_progression_boxplot_genotype_its2 <- ipam_fragments %>% 
  # filter(Gulf == "Chiriqui") %>%
  # filter(Gulf == "Panama") %>%
  ggplot(aes(DayF, mean_value, group = Treatment, color = Treatment, fill = Genotype)) + # linetype = Treatment
  geom_point(aes(color = Treatment), shape = 21, alpha = 0.8, position = position_dodge(0.25)) +
  # stat_summary(fun.data = "mean_cl_boot", geom = "errorbar", width = 0.2, position = position_dodge(0.25)) +
  # stat_summary(fun = mean, geom = "line") +
  # facet_nested(. ~ ITS2 + Genotype, scales = "free_x", space = "free", switch = NULL) +
  scale_color_manual(values = treatcolors[2:3]) +
  scale_fill_manual(values = genocolors) + 
  ylim(0.25, 0.75) +
  # labs(x = "Day", y = "Fv/Fm values") +
  ggtitle(title)
ipam_progression_boxplot_genotype_its2
# ggsave("./outputs/figures/ipam_progression_plot_genotype_its2.pdf", ipam_progression_boxplot_genotype_its2, device = "pdf", height = 5, width = 11)
# ITS2 type has a significant effect on Fv/Fm values
# PAN-37, PAN-39, PAN-83, (URA-51) are candidates for symbiont switching after Ana initally characterized them
```

```{r genotype_averages}
genotype_summary <- ipam_complete %>%
  group_by(Treatment, Genotype, Meas_Day) %>% 
  summarise(geno_mean_value = mean(mean_value)) %>% 
  filter(!is.na(Genotype))

genotype_summary$Treatment <- factor(genotype_summary$Treatment, levels = treatment_levels, ordered = TRUE)
```

```{r}
YII_Genotype <- ggplot(ipam_fragments, aes(DayF, mean_value, color = Genotype, group = Genotype)) +
  geom_point(alpha=0.3) +
  stat_summary(fun.data = "mean_se", geom = "errorbar", width = 0.2 ) + # or mean_cl_boot
  stat_summary(fun.y=mean, geom = "line") +
  scale_color_manual(values = genocolors) 

YII_Genotype + ylim(0.25, 0.7) + facet_grid(ITS2~Treatment)
YII_Genotype + ylim(0.25, 0.7) + facet_grid(mtORF~Treatment)
YII_Genotype + ylim(0.25, 0.7) + facet_grid(Location~Treatment)
```
```{r}
# Treatment 
YII_Treatment <- ggplot(ipam_fragments, aes(DayF, mean_value, colour=Treatment, group=Treatment)) +
  stat_summary(fun.data = "mean_se",geom = "errorbar", width = 0.2, position = position_dodge(0.1))+
  #stat_summary(fun.y=mean, geom="point", size =3, alpha=0.5) +
  stat_summary(fun.y=mean, geom="line") +
      scale_color_manual(values = treatcolors[2:3]) +
      scale_y_continuous(breaks = seq(0.4, 0.7, 0.1),  
                         name=("Photochemical efficiency (Fv/Fm)")) +
      scale_x_discrete(name="Day") +
    coord_cartesian(ylim=c(0.4, 0.7))
# YII_Treatment
# YII_Treatment + facet_wrap(~mtORF)
title <- expression(paste(italic("Pocillopora"), " Symbiodinaceae Fv/Fm values during experiment", collapse = ""))
YII_Treatment + facet_wrap(~ITS2) + ggtitle(title)
# YII_Treatment + facet_wrap(~Genotype)
# ggsave("./outputs/figures/ipam_progression_plot_its2_treatment.pdf", device = "pdf", height = 5, width = 11)
```
```{r dissertation figure 4.2}
ipam_plot <- ipam_fragments %>% ggplot(aes(DayF, mean_value, colour=Treatment, group=Treatment)) +
  stat_summary(fun.data = "mean_se",geom = "errorbar", width = 0.2, position = position_dodge(0.1))+
  stat_summary(fun.y=mean, geom="point", size = 2, alpha=0.8, position = position_dodge(0.1)) +
  stat_summary(fun.y=mean, geom="line") +
      scale_color_manual(values = treatcolors[2:3]) +
      scale_y_continuous(breaks = seq(0.4, 0.7, 0.1),  
                         name=("Photochemical efficiency (Fv/Fm)")) +
      scale_x_discrete(name="Day") +
    coord_cartesian(ylim=c(0.3, 0.7))

ipam_plot + facet_nested(. ~ mtORF + Symbiont_Genus, scales = "free_x", space = "free", switch = NULL)
ggsave("./outputs/figures/ipam_progression_plot_mtorf_symbiont.pdf", device = "pdf", height = 3.5, width = 6)
```

## Statistical analysis
### Summary statistics
```{r summary stats}
# Blank well Fv/Fm
ipam_complete %>% 
  filter(Sample_ID == "b") %>% 
  summarise(
    mean_fvfm = mean(mean_value),
    se_fvfm = se(mean_value)
  )
# Microfragment Fv/Fm
ipam_complete %>% 
  filter(Sample_ID != "b") %>% 
  summarise(
    mean_fvfm = mean(mean_value),
    se_fvfm = se(mean_value)
  )
# Microfragment Fv/Fm grouped by ITS2, Treatment
ipam_complete %>% 
  filter(Sample_ID != "b") %>%
  group_by(ITS2, Treatment) %>% 
  summarise(
    mean_fvfm = mean(mean_value),
    sedev_fvfm = se(mean_value)
  )
```
```{r normality_tests}
# Tests for normality 
shapiro.test(asin(ipam_fragments$mean_value))
# 
shapiro.test(ipam_tidied$value)

ggdensity(log(ipam_fragments$mean_value, base = exp(1)))
ggqqplot((ipam_fragments$mean_value))
# arcsine transform
ggdensity(asin(ipam_fragments$mean_value))
ggqqplot(asin(ipam_fragments$mean_value))
```
```{r two way anova}
# Two-way ANOVA to test significance of treatment and time factors
ipam_anova <- aov(mean_value ~ Treatment + Meas_Day + Treatment:Meas_Day, data = ipam_fragments)
summary(ipam_anova)
TukeyHSD(ipam_anova, which = c("Treatment", "Meas_Day"))
```

### Generalized linear models
```{r}
m1 <- lm(mean_value ~ Treatment, data = ipam_fragments)
m1
plot(m1)
m2 <- lm(mean_value ~ Treatment + Meas_Day, data = ipam_fragments)
# m3 <- lm(mean_value ~ Treatment * Meas_Day, data = ipam_fragments)

compare_parameters(m1, m2)
plot(compare_parameters(m1, m2, m3))

summary(m1)
# Other useful functions
coefficients(fit) # model coefficients
confint(fit, level=0.95) # CIs for model parameters
fitted(fit) # predicted values
residuals(fit) # residuals
anova(m1) # anova table
vcov(fit) # covariance matrix for model parameters
influence(fit) # regression diagnostics
# diagnostic plots
layout(matrix(c(1,2,3,4),2,2)) # optional 4 graphs/page
plot(m2)
# 
shapiro.test(residuals(m1))
```
```{r}
# Stepwise Regression
library("MASS")
fit <- lm(mean_value ~ Treatment + Meas_Day + Genotype, data = ipam_fragments)
step <- stepAIC(m1, direction="both")
step$anova # display results
```
```{r}
# Global test of model assumptions
library("gvlma")
gvmodel <- gvlma(m1)
summary(m1)
```

### Linear mixed-effect models
```{r lme libraries, include = FALSE}
# Libraries 
  library("lme4")
  library("multcomp")
  library("multcompView")
  library("emmeans")
  library("effects")
  library("lmerTest")
#https://ourcodingclub.github.io/tutorials/mixed-models/
#https://stats.stackexchange.com/questions/4700/what-is-the-difference-between-fixed-effect-random-effect-and-mixed-effect-mode
```
#### Model #1: Treatment x Day, random ITS2, mtORF effects
```{r lme model 1}
# If you use day as a factor:
# * mtORF and ITS2 considered random effects
# * Day (as factor, not numeric) and Treatment considered fixed effect (what you are really testing)
ipam_lme_1 <- lmer(mean_value ~ Treatment * DayF + 
                            (1|mtORF) + (1|Symbiont_Genus), REML=TRUE, data = ipam_fragments)
summary(ipam_lme_1)
#
anova(ipam_lme_1)
#
ranova(ipam_lme_1)
#
step(ipam_lme_1)
# Fv/Fm is significantly different between days, no significant treatment fixed effect
# Significant mtORF and ITS2 random effects  
```
```{r lme_1 effect plot}
# pdf("./outputs/figures/ipam/ipam_treatment_effect.pdf", width = 8, height = 6)
plot(Effect(c("Treatment","DayF"), ipam_lme_1), x.var="DayF",
     multiline = T, ci.style="bars", colors = treatcolors[2:3])
# Clear that there is no treatment effect after controlling for other random factors
# dev.off()
```
#### Model #2: Treatment x Day, random Genotype effect
```{r lme model 2}
ipam_lme_2 <- lmer(mean_value ~ Treatment * DayF + (1|Genotype), REML=TRUE, data = ipam_fragments)
#
summary(ipam_lme_2)
#
anova(ipam_lme_2)
#
ranova(ipam_lme_2)
#
step(ipam_lme_2)
```
```{r lme_2 effect plot}
# pdf("./outputs/figures/ipam/ipam_treatment_effect.pdf", width = 8, height = 6)
plot(Effect(c("Treatment","DayF"), ipam_lme_2), x.var="DayF",
     multiline = T, ci.style="bars", colors = treatcolors[2:3])
# Clear that there is no treatment effect after controlling for other random factors
# dev.off()
```
#### Model #3
```{r lme model 3: }
ipam_lme_3 <- lmer(mean_value ~ ITS2 + mtORF + (1|Treatment), REML=TRUE,  data= ipam_fragments)

anova(ipam_lme_3)
#
ranova(ipam_lme_3)
#
step(ipam_lme_3)
```
```{r}
#  Pair-wise comparisons
cld(emmeans(LM_3, specs = c("mtORF")))
cld(emmeans(LM_3, specs = c("ITS2")))
#write.csv(YIIAcerEmm, "YIIAcerEmm.csv")
```
## Summary
```{r}
sessionInfo()
```

