---
title: "AntibioticsPilot2_IPAM"
author: "Mike Connelly"
date: "4/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/Desktop/PAN10AntiExpt_040319")
```
```{r}
library(tidyverse)
library(ggplot2)
```

```{r}
IPAM <- read.csv("./analysis/Anti_040319_IPAM.csv")
IPAM$Fragment.ID. <- as.factor(IPAM$Fragment.ID.)
IPAM$Treatment <- factor(IPAM$Treatment, levels = c("Control", "Low-Anti", "High-Anti", "Very-High-Anti"), ordered = TRUE)
IPAM$Meas..Time <- factor(IPAM$Meas..Time, levels = c("tb", "t2", "t24"), ordered = TRUE)
```

```{r}
treatcolors <- c("#0000FF", "#00CCCC", "#339999", "#009966")
treatfills <- c("#99CCFF", "#99FFFF", "#66CCCC", "#99FFCC")
colshapes <- c(18, 9, 16, 10)
colcolors <- c("#CCFFCC", "#99FFCC", "#CCFFFF", "#99FFCC")
```


```{r}
#pdf(file = "./analysis/IPAMtime.pdf", width = , height = 4)
plot <- ggplot(IPAM, aes(x=Treatment, y=Fv.Fm, color=Treatment))
plot + 
  geom_boxplot(aes(fill=Treatment)) +
  geom_point() +
  facet_grid(~Meas..Time) +
  scale_color_manual(values = treatcolors) +
  scale_fill_manual(values = treatfills) + 
  theme(legend.position = "none")
```

```{r}
pdf(file = "./analysis/IPAMtreatment_proposal.pdf", width = 6, height = 4)
plot2 <- ggplot(IPAM, aes(x=Meas..Time, y=Fv.Fm, color=Treatment))
plot2 + 
  geom_boxplot(aes(fill=Treatment)) +
  geom_point() + 
  facet_grid(~Treatment) +
  scale_color_manual(values = treatcolors) +
  scale_fill_manual(values = treatfills) + 
  theme(legend.position = "bottom", text = element_text(size=16))
```

```{r}
#pdf(file = "./analysis/IPAMfragment.pdf", width = 6, height = 4)
plot3 <- ggplot(IPAM, aes(x=Meas..Time, y=Fv.Fm, color=Treatment))
plot3 + 
  geom_boxplot(aes(fill=Treatment)) + 
  geom_point() + 
  facet_grid(~Fragment.ID.) +
  scale_color_manual(values = treatcolors) +
  scale_fill_manual(values = treatfills)
```
```{r}
mean(IPAM$Fv.Fm)
```

Two-way ANOVA to test significance of treatment and time factors
```{r}
ipam.aov <- aov(Fv.Fm ~ Treatment + Meas..Time + Treatment:Meas..Time, data = IPAM)
summary(ipam.aov)
TukeyHSD(ipam.aov, which = c("Treatment", "Meas..Time"))
```
```{r}
ipam.geno.aov <- aov(Fv.Fm ~ Fragment.ID. + Meas..Time + Fragment.ID.:Meas..Time, data = IPAM)
summary(ipam.geno.aov)
TukeyHSD(ipam.geno.aov, which = c("Fragment.ID.", "Meas..Time"))
```
```{r}
IPAM_veryhigh <- filter(IPAM, Treatment=="Very-High-Anti")
IPAM_high <- filter(IPAM, Treatment=="High-Anti")
IPAM_low <- filter(IPAM, Treatment=="Low-Anti")
IPAM_ctrl <- filter(IPAM, Treatment=="Control")
```
```{r}
ipam.high.aov <- aov(Fv.Fm ~ Meas..Time + Fragment.ID. + Meas..Time:Fragment.ID., data = IPAM_high)
summary(ipam.high.aov)
TukeyHSD(ipam.high.aov, which = c("Meas..Time", "Fragment.ID."))
```
```{r}
ipam.low.aov <- aov(Fv.Fm ~ Meas..Time + Fragment.ID. + Meas..Time:Fragment.ID., data = IPAM_low)
summary(ipam.low.aov)
TukeyHSD(ipam.low.aov, which = c("Meas..Time", "Fragment.ID."))
```
```{r}
ipam.ctrl.aov <- aov(Fv.Fm ~ Meas..Time + Fragment.ID. + Meas..Time:Fragment.ID., data = IPAM_ctrl)
summary(ipam.ctrl.aov)
TukeyHSD(ipam.ctrl.aov, which = c("Meas..Time", "Fragment.ID."))
```

