#!/bin/bash
#BSUB -q general
#BSUB -J URA-51_Antibiotics_153_trim
#BSUB -o "/scratch/projects/transcriptomics/mikeconnelly/projects/anti_phys"/outputs/logfiles/URA-51_Antibiotics_153_trim.out
#BSUB -e "/scratch/projects/transcriptomics/mikeconnelly/projects/anti_phys"/outputs/errorfiles/URA-51_Antibiotics_153_trim.err
module load java/1.8.0_60
echo Trimming URA-51_Antibiotics_153
~/programs/bbmap/bbduk.sh -Xmx512m \
in=/scratch/projects/transcriptomics/mikeconnelly/projects/anti_phys/data/quantseq_reads/URA-51_Antibiotics_153.fastq \
out=/scratch/projects/transcriptomics/mikeconnelly/projects/anti_phys/outputs/trimmed_reads/URA-51_Antibiotics_153_trimmed.fastq \
ref=/scratch/projects/transcriptomics/mikeconnelly/projects/anti_phys/data/bbmap_resources/polyA.fa.gz,/scratch/projects/transcriptomics/mikeconnelly/projects/anti_phys/data/bbmap_resources/truseq_rna.fa.gz \
k=13 \
ktrim=r \
useshortkmers=T \
mink=5 \
qtrim=10 \
minlength=20
echo URA-51_Antibiotics_153 successfully trimmed
